<a href="https://colab.research.google.com/github/michellefengym-glitch/Market-Analysis/blob/main/Capstone_Market_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Retail Sales and Customer Purchase Analysis**

*   Prepared by: Feng Yuanmei
*   Dataset Used: Market Analysis

## **1. Data import**

In [ ]:
# Importing the initial required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

purchase_url = "https://raw.githubusercontent.com/michellefengym-glitch/Market-Analysis/refs/heads/main/purchase.csv"
customer_url = "https://raw.githubusercontent.com/michellefengym-glitch/Market-Analysis/refs/heads/main/customer.csv"

purchases = pd.read_csv(purchase_url)
customers = pd.read_csv(customer_url)

print("Purchase Data:")
purchases.info()
display(purchases.head())

print("Customer Data:")
customers.info()
display(customers.head())

Purchase Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       50000 non-null  object
 1   customer_id    50000 non-null  object
 2   product_name   50000 non-null  object
 3   description    50000 non-null  object
 4   price          50000 non-null  float64
 5   discount       50000 non-null  float64
 6   tax            50000 non-null  float64
 7   order_date     50000 non-null  object
 8   quantity       50000 non-null  int64
 9   shipping_cost  50000 non-null  float64
 10  shipping_date  50000 non-null  object
dtypes: float64(4), int64(1), object(6)
memory usage: 4.2+ MB

,order_id,customer_id,product_name,description,price,discount,tax,order_date,quantity,shipping_cost,shipping_date
0,ODSHP00001,CS00001,Furniture,Transform your space with this stylish and fun...,645.52,0.37,0.02,26-05-2020,9,8.91,29-05-2020
1,ODSHP00002,CS00002,Dress,Look and feel your best with this elegant dress.,28.90,0.05,0.02,29-12-2022,9,13.95,29-12-2022
2,ODSHP00003,CS00003,Furniture,Transform your space with this stylish and fun...,3536.49,0.21,0.04,06-03-2021,3,36.42,06-03-2021
3,ODSHP00004,CS00004,Shoes,Step out in style with these fashionable shoes.,97.80,0.11,0.08,11-03-2020,7,9.35,13-03-2020
4,ODSHP00005,CS00005,Rugs,Add warmth and texture to your floors with the...,1785.38,0.13,0.00,12-03-2022,7,8.55,15-03-2022

Customer Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1001 non-null   object
 1   first_name   1001 non-null   object
 2   last_name    1001 non-null   object
 3   gender       1001 non-null   object
 4   age          1001 non-null   int64
 5   country      1001 non-null   object
 6   income       1001 non-null   int64
dtypes: int64(2), object(5)
memory usage: 54.9+ KB

  customer_id     first_name last_name  gender  age country  income
0     CS00001        Isadora     Porto  Female   19  Brazil  117196
1     CS00002           Hugo   Carreño    Male   33   Chile   49256
2     CS00003           René   Olivera    Male   65  Mexico   33434
3     CS00004  Luiz Henrique     Pinto    Male   55  Brazil   75302
4     CS00005       Leonardo  Monteiro    Male   19  Brazil   32280

## **2. Data Cleansing & Preparation**

We'll identify missing values, handle empty rows, correct data types, and prepare the dataset for analysis.

In [ ]:
# Missing values
print("Purchase missing values:")
display(purchases.isna().sum())

print("Customer missing values:")
display(customers.isna().sum())

# Duplicate rows
print("Duplicate purchase rows:", purchases.duplicated().sum())
print("Duplicate customer rows:", customers.duplicated().sum())

# Duplicate ID
print("Duplicate order IDs:",
      purchases["order_id"].duplicated().sum())

print("Duplicate customer IDs:",
      customers["customer_id"].duplicated().sum())

Purchase missing values:

order_id         0
customer_id      0
product_name     0
description      0
price            0
discount         0
tax              0
order_date       0
quantity         0
shipping_cost    0
shipping_date    0
dtype: int64

Customer missing values:

customer_id    0
first_name     0
last_name      0
gender         0
age            0
country        0
income         0
dtype: int64

Duplicate purchase rows: 0
Duplicate customer rows: 0
Duplicate order IDs: 0
Duplicate customer IDs: 0

# Initial Data Quality Findings

No missing values were identified in either dataset. No duplicate rows were found, and the order IDs in the purchase table and customer IDs in the customer table are unique. Therefore, no missing-value imputation or duplicate removal is required at this stage.